<h1>Registro</h1>


<!-- <form method="post">
    <input name="firstname" type="text">
    <input name="lastname" type="text">
    <input name="phone" type="text">
    <input name="bookingTime" type="date">
    <input type="submit" value="Send booking informations">
</form> -->


<form class="form create account form-create-account" method="post" id="form-validate"  autocomplete="off" novalidate="novalidate" action="<?php echo $block->getFormAction() ?>">
    <fieldset class="fieldset create info">
        <legend class="legend"><span>Información personal</span></legend><br>

            <div class="field field-name-firstname required">
                <label class="label" for="firstname"><span>Nombre</span></label>
                <div class="control">
                    <input type="text" id="firstname" name="firstname" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
            </div>
            <div class="field field-name-lastname required">
                <label class="label" for="lastname"><span>Apellidos</span></label>
                <div class="control">
                    <input type="text" id="lastname" name="lastname" value="" title="Last Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
            </div>
            <div class="field field-name-lastname required">
                <label class="label" for="lastname"><span>Email</span></label>
                <div class="control">
                    <input type="text" id="email" name="email" value="" title="Teléfono" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
            </div>
            
            <div class="field field-name-lastname required">
                <label class="label" for="lastname"><span>Teléfono</span></label>
                <div class="control">
                    <input type="text" id="phone" name="phone" value="" title="Teléfono" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
            </div>
            
    </fieldset>
          

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Registrar">
                <span>Registrar</span>
            </button>
        </div>
    </div>
</form>