

<script type="text/javascript">
require([
    "jquery",
    "mage/calendar"
], function($){
  $('#datepicker').datepicker({
       prevText: '&#x3c;zurück', prevStatus: '',
        prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
        nextText: 'Vor&#x3e;', nextStatus: '',
        nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
        monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
        'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
        monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun',
        'Jul','Ago','Sep','Oct','Nov','Dic'],
        dayNames: ['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],
        dayNamesShort: ['Do','Lu','Ma','Mi','Jue','Vie','Sab'],
        dayNamesMin: ['Do','Lu','Ma','Mi','Jue','Vie','Sab'],
      showMonthAfterYear: false,
      dateFormat:'dd-mm-yy'
    } 
  );
});
</script>
<form class="form create account form-create-account" method="post" id="form-validate"  autocomplete="off"  action="" data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset create info">
        <legend class="legend"><span>Datos de la cita</span></legend><br>

            <div class="field field-name-location required">
                <label class="label" for="location"><span>Comparte tu dirección</span></label>
                <div class="control">
                    <input type="text" id="location" name="location" value="" title="Dirección" class="input-text required-entry letters-only" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
            </div>
            <div class="field field-name-consultorio required">
                <label class="label" for="consultorio"><span>Consultorio</span></label>
                <div class="control">
                    <select id="consultorio" name="consultorio">
                        <option value="1">Miguel Hidalgo</option>
                        <option value="2">Azcapotzalco</option>
                        <option value="2">Guerrero</option>
                    </select>
                </div>
            </div>
            <div class="field field-name-dia required">
                <label class="label" for="dia"><span>Día</span></label>
                <div class="control">
                    <!-- <input type="text" id="dia" name="dia" value="" title="Día" class="input-text" data-validate="{required:true}" autocomplete="off" aria-required="true"> -->
                    <input name="terminwunsch" id="datepicker" title="Terminwunsch" value="" type="text">
                    <script type="text/javascript">
                    require([
                        "jquery",
                        "mage/calendar"
                        ], function($){
                          $('#datepicker').datepicker();
                        });
                    </script>
                </div>
            </div>
            
            <div class="field field-name-hora required">
                <label class="label" for="hora"><span>Hora</span></label>
                <div class="control">
                    <input type="time" id="hora" name="hora" value="" title="Hora" class="input-text" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
            </div>
            
    </fieldset>
          

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Next">
                <span>Siguiente</span>
            </button>
        </div>
    </div>
</form>