<h2>Listado de vacunas</h2>
<div id="modal-content" style="display:none;">
<form class="form " method="post" id="update-vacuna"  autocomplete="off"   data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset create info">
            <div class="field field-name-dia required">
                <label class="label" for="day"><span>Día</span></label>
                <div class="control">
                    <input name="idVacuna" id="idVacuna" value="" type="hidden">
                    <input name="day" id="datepicker" title="Fecha de cita" value="" type="text">
                </div>
            </div>
            <div class="field field-name-hora required">
                <label class="label" for="hour"><span>Hora</span></label>
                <div class="control">
                    <input type="time" id="hour" name="hour" value="" title="Hora" class="input-text" data-validate="{required:true}" autocomplete="off" aria-required="true">
                </div>
            </div>
    </fieldset>
</form>
</div>


<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}
#modal-content{
    height:200px;
    width:100px;
}

</style>

<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
            <tr>
                <th class="book-name">Folio</th>
                <th class="last_name">Consultorio</th>
                <th class="book_email">Fecha / hora </th>
                <th class="book_phone">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $data = (array)json_decode($block->getPostCollection(), true);
                if(count($data)>0){
                        foreach ($data as $item){
                            echo '<tr>
                                <td>'.$item['name'].'</td>
                                <td>'.$item['consultorio_id'].'</td>
                                <td>'.$item['date_time'].'</td>
                                <td>
                                    <button id="'.$item['appointment_vaccine_id'].'" datetime="'.$item['date_time'].'" class="edit click-me">Editar</button>
                                    <button id="'.$item['appointment_vaccine_id'].'" class="delete" >Eliminar</button>
                                
                                </td>
                            </tr>';
                        }
                    }

                
                    
                
                ?>
        </tbody>
    </table>    
</div>    